[package]
name = "eh_rogue_mod"
version = "0.1.0"
edition = "2021"

[dependencies]
eh_mod_cli = { workspace = true }
pretty-duration = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde"]
